version: '3'

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.11
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - traefik
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml

  blue-web: &web
    container_name: blue-web
    build:
      context: ../
      dockerfile: infra/Dockerfile
      network: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blue-web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.blue-web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - traefik

  green-web:
    <<: *web
    container_name: green-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green-web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.green-web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"

networks:
  traefik:
    name: traefik_webgateway
    external: true
    driver: bridge
