name: Build the Restaurant service
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: |
            - ~/.m2
            - ~/.gitlibs
          key: cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: clojure-deps-

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.12.0.1479
          cljfmt: 0.12.0
          clj-kondo: 2024.08.29

      - name: Check formatting
        run: cljfmt check deps.edn src dev infra

      - name: Lint application
        run: |
          clj-kondo --lint deps.edn src dev
          #clojure -M:dev:test:linters -m eastwood.lint
          #clojure -M:dev:test:linters -m noahtheduke.splint

      - name: Lint infrastructure
        run: |
          clj-kondo --lint infra
          #clojure -M:build:upgrade:linters -m eastwood.lint
          #clojure -M:build:upgrade:linters -m noahtheduke.splint

      - name: Run tests
        run: clojure -X:test

      - name: Setup deployment controller
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy service
        run: flyctl deploy --config infra/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
