name: Build the Restaurant service
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: |
            - ~/.m2
            - ~/.gitlibs
          key: cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: clojure-deps-

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.12.0.1495
          cljfmt: 0.13.0
          clj-kondo: 2024.11.14

      - name: Check formatting
        run: cljfmt check deps.edn src test infra dev

      - name: Lint the code base
        run: |
          clj-kondo --lint deps.edn src test infra dev
          clojure -X:dev:test user/lint

      - name: Run tests
        run: clojure -X:test

      - name: Run data migration
        run: clojure -X:migrations migrate
        env:
          RESTAURANT_DATABASE_PASSWORD: ${{ secrets.RESTAURANT_DATABASE_PASSWORD }}

      - name: Setup deployment controller
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy service
        run: flyctl deploy --config infra/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
